[supervisord]
nodaemon=true
user=root
# Лог самого супервизора (в консоль докера)
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

# --- FASTAPI ---
[program:fastapi]
command=uvicorn worker_main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
# Вывод напрямую в stdout контейнера
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- ENGINE ---
[program:engine]
command=python worker_engine.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- CONNECTOR ---
[program:connector]
command=python worker_connector.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- TG BOT & SERVICES ---
[program:services]
command=python worker_services.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

# --- SCHEDULER ---
[program:scheduler]
command=python worker_scheduler.py
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0